services:
  database:
    image: docker.io/postgres:14-bookworm
    restart: always
    volumes: 
      - ./data/test_db/:/var/lib/postgresql/data
      - ./migrate/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=mhealthy-server
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mhealthy
    ports:
      - 5432:5432
